/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const AdjustmentFormDialog: typeof import('./renderer/features/inventory-adjustments/ui/adjustment-form-dialog').AdjustmentFormDialog
  const AdjustmentsPage: typeof import('./renderer/pages/adjustments-page').AdjustmentsPage
  const AdjustmentsTable: typeof import('./renderer/features/inventory-adjustments/ui/adjustments-table').AdjustmentsTable
  const AppSidebar: typeof import('./renderer/components/sidebar/app-sidebar').AppSidebar
  const Badge: typeof import('@heroui/react').Badge
  const BreadcrumbItem: typeof import('@heroui/react').BreadcrumbItem
  const Breadcrumbs: typeof import('@heroui/react').Breadcrumbs
  const Button: typeof import('@heroui/react').Button
  const CashPage: typeof import('./renderer/pages/cash-page').CashPage
  const CashRegisterForm: typeof import('./renderer/features/cash-sessions/components/cash-register-form').CashRegisterForm
  const CashRegistersList: typeof import('./renderer/features/cash-sessions/components/cash-registers-list').CashRegistersList
  const CashSessionManager: typeof import('./renderer/features/cash-sessions/components/cash-session-manager').CashSessionManager
  const CategoriesEmptyState: typeof import('./renderer/features/categories/ui/categories-empty-state').CategoriesEmptyState
  const CategoriesFilters: typeof import('./renderer/features/categories/ui/catgories-filters').CategoriesFilters
  const CategoriesHeader: typeof import('./renderer/features/categories/ui/categories-header').CategoriesHeader
  const CategoriesPage: typeof import('./renderer/pages/categories-page').CategoriesPage
  const CategoriesTable: typeof import('./renderer/features/categories/ui/categories-table').CategoriesTable
  const CategoriesTableContent: typeof import('./renderer/features/categories/ui/categories-table-content').CategoriesTableContent
  const CategoriesTableHeader: typeof import('./renderer/features/categories/ui/categories-table-header').CategoriesTableHeader
  const CategoriesTableRow: typeof import('./renderer/features/categories/ui/categories-table-row').CategoriesTableRow
  const CategoryForm: typeof import('./renderer/features/categories/ui/category-form').CategoryForm
  const CategoryFormDialog: typeof import('./renderer/features/categories/ui/category-form-dialog').CategoryFormDialog
  const CategoryFormFields: typeof import('./renderer/features/categories/ui/category-form-fields').CategoryFormFields
  const CategorySales: typeof import('./renderer/features/reports/components/category-sales').CategorySales
  const CategorySelect: typeof import('./renderer/features/products/ui/category-select').CategorySelect
  const Chip: typeof import('@heroui/react').Chip
  const ComingSoon: typeof import('./shared/components/ComingSoon').ComingSoon
  const Controller: typeof import('react-hook-form').Controller
  const CreatePresentationButton: typeof import('./renderer/features/presentations/ui/create-presentation-button').CreatePresentationButton
  const CreditsPage: typeof import('./renderer/pages/credits-page').CreditsPage
  const CustomerFormDialog: typeof import('./renderer/features/customers/ui/customer-form-dialog').CustomerFormDialog
  const CustomersPage: typeof import('./renderer/pages/customers-page').CustomersPage
  const CustomersTable: typeof import('./renderer/features/customers/ui/customers-table').CustomersTable
  const DashboardPage: typeof import('./renderer/pages/dashboard-page').DashboardPage
  const Debts: typeof import('./renderer/features/reports/components/debts').Debts
  const DeleteProductDialog: typeof import('./renderer/features/products/ui/delete-product-dialog').DeleteProductDialog
  const Divider: typeof import('@heroui/react').Divider
  const EMPTY_CATEGORY_FORM: typeof import('./renderer/features/categories/model/category-constants').EMPTY_CATEGORY_FORM
  const EMPTY_INVENTORY_ITEM: typeof import('./renderer/features/inventory/model/inventory-entry-constants').EMPTY_INVENTORY_ITEM
  const EMPTY_PRESENTATION_FORM: typeof import('./renderer/features/presentations/model/presentation-constants').EMPTY_PRESENTATION_FORM
  const EMPTY_PRODUCT_FORM: typeof import('./renderer/features/products/model/product-constants').EMPTY_PRODUCT_FORM
  const ExpensesPage: typeof import('./renderer/pages/expenses-page').ExpensesPage
  const ExpirationStatusCell: typeof import('./renderer/features/inventory/batches/ui/expiration-status-cell').ExpirationStatusCell
  const FormProvider: typeof import('react-hook-form').FormProvider
  const Fragment: typeof import('react').Fragment
  const HelpPage: typeof import('./renderer/pages/help-page').HelpPage
  const HeroUIProvider: typeof import('@heroui/react').HeroUIProvider
  const INVENTORY_BATCH_COLUMNS: typeof import('./renderer/features/inventory/batches/model/inventory-batches-columns').INVENTORY_BATCH_COLUMNS
  const INVENTORY_ENTRY_DEFAULTS: typeof import('./renderer/features/inventory/model/inventory-entry-constants').INVENTORY_ENTRY_DEFAULTS
  const INVENTORY_MOVEMENT_COLUMNS: typeof import('./renderer/features/inventory/movements/model/movement-columns').INVENTORY_MOVEMENT_COLUMNS
  const IconLucideCalendar: typeof import('~icons/lucide/calendar.tsx').default
  const IconLucideCheck: typeof import('~icons/lucide/check.tsx').default
  const IconLucideChevronLeft: typeof import('~icons/lucide/chevron-left.tsx').default
  const IconLucideChevronRight: typeof import('~icons/lucide/chevron-right.tsx').default
  const IconLucideChevronsLeft: typeof import('~icons/lucide/chevrons-left.tsx').default
  const IconLucideChevronsRight: typeof import('~icons/lucide/chevrons-right.tsx').default
  const IconLucideChevronsUpDown: typeof import('~icons/lucide/chevrons-up-down.tsx').default
  const IconLucideEdit: typeof import('~icons/lucide/edit.tsx').default
  const IconLucideFolderOpen: typeof import('~icons/lucide/folder-open.tsx').default
  const IconLucideHistory: typeof import('~icons/lucide/history.tsx').default
  const IconLucideMoreHorizontal: typeof import('~icons/lucide/more-horizontal.tsx').default
  const IconLucidePackage: typeof import('~icons/lucide/package.tsx').default
  const IconLucidePlus: typeof import('~icons/lucide/plus.tsx').default
  const IconLucideSearch: typeof import('~icons/lucide/search.tsx').default
  const IconLucideTrash: typeof import('~icons/lucide/trash.tsx').default
  const IconLucideTrash2: typeof import('~icons/lucide/trash2.tsx').default
  const IconLucideX: typeof import('~icons/lucide/x.tsx').default
  const IconSolarAddCircleLineDuotone: typeof import('~icons/solar/add-circle-line-duotone.tsx').default
  const IconSolarArrowLeftLinear: typeof import('~icons/solar/arrow-left-linear.tsx').default
  const IconSolarArrowRightDownLinear: typeof import('~icons/solar/arrow-right-down-linear.tsx').default
  const IconSolarArrowRightLinear: typeof import('~icons/solar/arrow-right-linear.tsx').default
  const IconSolarArrowRightUpLinear: typeof import('~icons/solar/arrow-right-up-linear.tsx').default
  const IconSolarBanknote2Linear: typeof import('~icons/solar/banknote2-linear.tsx').default
  const IconSolarBanknoteLinear: typeof import('~icons/solar/banknote-linear.tsx').default
  const IconSolarBellOutline: typeof import('~icons/solar/bell-outline.tsx').default
  const IconSolarBillListLinear: typeof import('~icons/solar/bill-list-linear.tsx').default
  const IconSolarBoxLinear: typeof import('~icons/solar/box-linear.tsx').default
  const IconSolarCalendarLinear: typeof import('~icons/solar/calendar-linear.tsx').default
  const IconSolarCalendarMinimalisticLinear: typeof import('~icons/solar/calendar-minimalistic-linear.tsx').default
  const IconSolarCartCrossLineDuotone: typeof import('~icons/solar/cart-cross-line-duotone.tsx').default
  const IconSolarCartLarge2LineDuotone: typeof import('~icons/solar/cart-large2-line-duotone.tsx').default
  const IconSolarCheckCircleBoldDuotone: typeof import('~icons/solar/check-circle-bold-duotone.tsx').default
  const IconSolarChecklistMinimalisticLinear: typeof import('~icons/solar/checklist-minimalistic-linear.tsx').default
  const IconSolarClipboardListLinear: typeof import('~icons/solar/clipboard-list-linear.tsx').default
  const IconSolarCloseCircleBoldDuotone: typeof import('~icons/solar/close-circle-bold-duotone.tsx').default
  const IconSolarCopyLinear: typeof import('~icons/solar/copy-linear.tsx').default
  const IconSolarDocumentAddLinear: typeof import('~icons/solar/document-add-linear.tsx').default
  const IconSolarDocumentTextLinear: typeof import('~icons/solar/document-text-linear.tsx').default
  const IconSolarHandMoneyLinear: typeof import('~icons/solar/hand-money-linear.tsx').default
  const IconSolarHistoryLinear: typeof import('~icons/solar/history-linear.tsx').default
  const IconSolarHome2Linear: typeof import('~icons/solar/home2-linear.tsx').default
  const IconSolarInfoCircleLinear: typeof import('~icons/solar/info-circle-linear.tsx').default
  const IconSolarLaptopMinimalisticLinear: typeof import('~icons/solar/laptop-minimalistic-linear.tsx').default
  const IconSolarMagniferOutline: typeof import('~icons/solar/magnifer-outline.tsx').default
  const IconSolarMenuDotsLinear: typeof import('~icons/solar/menu-dots-linear.tsx').default
  const IconSolarMinimalisticMagniferLineDuotone: typeof import('~icons/solar/minimalistic-magnifer-line-duotone.tsx').default
  const IconSolarMinusCircleLineDuotone: typeof import('~icons/solar/minus-circle-line-duotone.tsx').default
  const IconSolarMoneyBagLinear: typeof import('~icons/solar/money-bag-linear.tsx').default
  const IconSolarPauseCircleLineDuotone: typeof import('~icons/solar/pause-circle-line-duotone.tsx').default
  const IconSolarPauseLineDuotone: typeof import('~icons/solar/pause-line-duotone.tsx').default
  const IconSolarPenLinear: typeof import('~icons/solar/pen-linear.tsx').default
  const IconSolarPenNewSquareBoldDuotone: typeof import('~icons/solar/pen-new-square-bold-duotone.tsx').default
  const IconSolarPresentationGraphLinear: typeof import('~icons/solar/presentation-graph-linear.tsx').default
  const IconSolarRefreshSquareLinear: typeof import('~icons/solar/refresh-square-linear.tsx').default
  const IconSolarRoundArrowDownLinear: typeof import('~icons/solar/round-arrow-down-linear.tsx').default
  const IconSolarRoundArrowUpLinear: typeof import('~icons/solar/round-arrow-up-linear.tsx').default
  const IconSolarRoundSortVerticalLinear: typeof import('~icons/solar/round-sort-vertical-linear.tsx').default
  const IconSolarSafe2Linear: typeof import('~icons/solar/safe2-linear.tsx').default
  const IconSolarSaleLinear: typeof import('~icons/solar/sale-linear.tsx').default
  const IconSolarScooterLinear: typeof import('~icons/solar/scooter-linear.tsx').default
  const IconSolarSettingsMinimalisticLinear: typeof import('~icons/solar/settings-minimalistic-linear.tsx').default
  const IconSolarSettingsOutline: typeof import('~icons/solar/settings-outline.tsx').default
  const IconSolarShieldWarningLineDuotone: typeof import('~icons/solar/shield-warning-line-duotone.tsx').default
  const IconSolarSiderbarLineDuotone: typeof import('~icons/solar/siderbar-line-duotone.tsx').default
  const IconSolarSirenRoundedLineDuotone: typeof import('~icons/solar/siren-rounded-line-duotone.tsx').default
  const IconSolarSmartphoneUpdateLinear: typeof import('~icons/solar/smartphone-update-linear.tsx').default
  const IconSolarSortHorizontalLinear: typeof import('~icons/solar/sort-horizontal-linear.tsx').default
  const IconSolarSunOutline: typeof import('~icons/solar/sun-outline.tsx').default
  const IconSolarTicketSaleLinear: typeof import('~icons/solar/ticket-sale-linear.tsx').default
  const IconSolarTrashBinMinimalisticBoldDuotone: typeof import('~icons/solar/trash-bin-minimalistic-bold-duotone.tsx').default
  const IconSolarTrashBinMinimalisticLineDuotone: typeof import('~icons/solar/trash-bin-minimalistic-line-duotone.tsx').default
  const IconSolarTuning2Linear: typeof import('~icons/solar/tuning2-linear.tsx').default
  const IconSolarUsersGroupTwoRoundedLinear: typeof import('~icons/solar/users-group-two-rounded-linear.tsx').default
  const IconSolarWalletMoneyLinear: typeof import('~icons/solar/wallet-money-linear.tsx').default
  const IconSolarWidget2BoldDuotone: typeof import('~icons/solar/widget2-bold-duotone.tsx').default
  const IconSolarWidget2Outline: typeof import('~icons/solar/widget2-outline.tsx').default
  const Input: typeof import('@heroui/react').Input
  const InventoryBatchesTable: typeof import('./renderer/features/inventory/batches/ui/inventory-batches-table').InventoryBatchesTable
  const InventoryBatchesTableActions: typeof import('./renderer/features/inventory/batches/ui/inventory-batches-table-actions').InventoryBatchesTableActions
  const InventoryBatchesTableEmpty: typeof import('./renderer/features/inventory/batches/ui/inventory-batches-table-empty').InventoryBatchesTableEmpty
  const InventoryBatchesTableHeader: typeof import('./renderer/features/inventory/batches/ui/inventory-batches-table-header').InventoryBatchesTableHeader
  const InventoryBatchesTableRow: typeof import('./renderer/features/inventory/batches/ui/inventory-batches-table-row').InventoryBatchesTableRow
  const InventoryEntryForm: typeof import('./renderer/features/inventory/ui/inventory-entry-form').InventoryEntryForm
  const InventoryEntryFormFields: typeof import('./renderer/features/inventory/ui/inventory-entry-form-fields').InventoryEntryFormFields
  const InventoryEntryFormHeader: typeof import('./renderer/features/inventory/ui/inventory-entry-form-header').InventoryEntryFormHeader
  const InventoryEntryFormRow: typeof import('./renderer/features/inventory/ui/inventory-entry-form-row').InventoryEntryFormRow
  const InventoryEntryPage: typeof import('./renderer/pages/inventory-entry-page').InventoryEntryPage
  const InventoryMovementsTable: typeof import('./renderer/features/inventory/movements/ui/inventory-movements-table').InventoryMovementsTable
  const InventoryPage: typeof import('./renderer/pages/inventory-page').InventoryPage
  const Kbd: typeof import('@heroui/react').Kbd
  const Layout: typeof import('./renderer/layout').Layout
  const Link: typeof import('react-router-dom').Link
  const LowStock: typeof import('./renderer/features/reports/components/low-stock').LowStock
  const MeasurementUnitBadge: typeof import('./renderer/components/badges/measurement-unit-badge').MeasurementUnitBadge
  const NavLink: typeof import('react-router-dom').NavLink
  const NavMain: typeof import('./renderer/components/sidebar/nav-main').NavMain
  const NavMainItem: typeof import('./renderer/components/sidebar/nav-main-item').NavMainItem
  const NavMainSubItem: typeof import('./renderer/components/sidebar/nav-main-sub-item').NavMainSubItem
  const NavSecondary: typeof import('./renderer/components/sidebar/nav-secondary').NavSecondary
  const NavUser: typeof import('./renderer/components/sidebar/nav-user').NavUser
  const Navigate: typeof import('react-router-dom').Navigate
  const NewReturnDialog: typeof import('./renderer/features/returns/ui/new-return-dialog').NewReturnDialog
  const NotFoundPage: typeof import('./renderer/pages/not-found-page').NotFoundPage
  const Outlet: typeof import('react-router-dom').Outlet
  const POSInterface: typeof import('./renderer/features/pos/components/pos-interface').POSInterface
  const PRODUCT_STATUSES: typeof import('./renderer/features/products/model/product-status').PRODUCT_STATUSES
  const Pagination: typeof import('@heroui/react').Pagination
  const PosCartItem: typeof import('./renderer/features/pos/components/pos-cart-item').PosCartItem
  const PosChargeModal: typeof import('./renderer/features/pos/components/pos-charge-modal').PosChargeModal
  const PosItem: typeof import('./renderer/features/pos/components/pos-item').PosItem
  const PosPage: typeof import('./renderer/pages/pos-page').PosPage
  const PresentationForm: typeof import('./renderer/features/presentations/ui/presentation-form').PresentationForm
  const PresentationFormDialog: typeof import('./renderer/features/presentations/ui/presentation-form-dialog').PresentationFormDialog
  const PresentationFormFields: typeof import('./renderer/features/presentations/ui/presentation-form-fields').PresentationFormFields
  const PresentationsTable: typeof import('./renderer/features/presentations/ui/presentations-table').PresentationsTable
  const PresentationsTableActions: typeof import('./renderer/features/presentations/ui/presentations-table-actions').PresentationsTableActions
  const PresentationsTableRow: typeof import('./renderer/features/presentations/ui/presentations-table-row').PresentationsTableRow
  const ProductForm: typeof import('./renderer/features/products/ui/product-form').ProductForm
  const ProductFormDialog: typeof import('./renderer/features/products/ui/product-form-dialog').ProductFormDialog
  const ProductFormDialogContent: typeof import('./renderer/features/products/ui/product-form-dialog-content').ProductFormDialogContent
  const ProductFormFields: typeof import('./renderer/features/products/ui/product-form-fields').ProductFormFields
  const ProductImage: typeof import('./renderer/features/products/ui/product-image').ProductImage
  const ProductImagePicker: typeof import('./renderer/features/products/ui/product-image-picker').ProductImagePicker
  const ProductPresentationsDialog: typeof import('./renderer/features/products/ui/product-presentations-dialog').ProductPresentationsDialog
  const ProductSelect: typeof import('./renderer/features/inventory/ui/product-select').ProductSelect
  const ProductsEmptyState: typeof import('./renderer/features/products/ui/products-empty-state').ProductsEmptyState
  const ProductsFilters: typeof import('./renderer/features/products/ui/products-filters').ProductsFilters
  const ProductsHeader: typeof import('./renderer/features/products/ui/products-header').ProductsHeader
  const ProductsPage: typeof import('./renderer/pages/products-page').ProductsPage
  const ProductsTable: typeof import('./renderer/features/products/ui/products-table').ProductsTable
  const ProductsTableActions: typeof import('./renderer/features/products/ui/products-table-actions').ProductsTableActions
  const ProductsTableContent: typeof import('./renderer/features/products/ui/products-table-content').ProductsTableContent
  const ProductsTableHeader: typeof import('./renderer/features/products/ui/products-table-header').ProductsTableHeader
  const ProductsTableRow: typeof import('./renderer/features/products/ui/products-table-row').ProductsTableRow
  const PurchaseOrderFormDialog: typeof import('./renderer/features/purchase-orders/ui/purchase-order-form-dialog').PurchaseOrderFormDialog
  const PurchaseOrdersPage: typeof import('./renderer/pages/purchase-orders-page').PurchaseOrdersPage
  const PurchaseOrdersTable: typeof import('./renderer/features/purchase-orders/ui/purchase-orders-table').PurchaseOrdersTable
  const QueryClient: typeof import('@tanstack/react-query').QueryClient
  const QueryClientProvider: typeof import('@tanstack/react-query').QueryClientProvider
  const ReportsPage: typeof import('./renderer/pages/reports-page').ReportsPage
  const ReturnsPage: typeof import('./renderer/pages/returns-page').ReturnsPage
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const SalesPage: typeof import('./renderer/pages/sales-page').SalesPage
  const SettingsPage: typeof import('./renderer/pages/settings-page').SettingsPage
  const Spinner: typeof import('@heroui/react').Spinner
  const StatusBadge: typeof import('./renderer/components/badges/status-badge').StatusBadge
  const SupplierFormDialog: typeof import('./renderer/features/suppliers/ui/supplier-form-dialog').SupplierFormDialog
  const SupplierSelect: typeof import('./renderer/features/inventory/ui/supplier-select').SupplierSelect
  const SuppliersPage: typeof import('./renderer/pages/suppliers-page').SuppliersPage
  const SuppliersTable: typeof import('./renderer/features/suppliers/ui/suppliers-table').SuppliersTable
  const Suspense: typeof import('react').Suspense
  const Tab: typeof import('@heroui/react').Tab
  const Table: typeof import('@heroui/react').Table
  const TableBody: typeof import('@heroui/react').TableBody
  const TableCell: typeof import('@heroui/react').TableCell
  const TableColumn: typeof import('@heroui/react').TableColumn
  const TableFacetedFilter: typeof import('./renderer/components/table/table-faceted-filter').TableFacetedFilter
  const TableHeader: typeof import('@heroui/react').TableHeader
  const TablePagination: typeof import('./renderer/components/table/table-pagination').TablePagination
  const TableRow: typeof import('@heroui/react').TableRow
  const Tabs: typeof import('@heroui/react').Tabs
  const ToastProvider: typeof import('@heroui/react').ToastProvider
  const Tooltip: typeof import('@heroui/react').Tooltip
  const TopProducts: typeof import('./renderer/features/reports/components/top-products').TopProducts
  const UNIT_CONFIG: typeof import('./renderer/features/products/ui/product-units').UNIT_CONFIG
  const Units: typeof import('./renderer/features/products/ui/product-units').Units
  const adjustmentAdapter: typeof import('./renderer/features/inventory-adjustments/api/adjustment-adapter').adjustmentAdapter
  const batchSchema: typeof import('./renderer/features/inventory/batches/model/inventory-batch-schema').batchSchema
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const capitalize: typeof import('./shared/utils/string').capitalize
  const cashSessionManager: typeof import('./renderer/features/cash-sessions/components/cash-session-manager').default
  const categoryAdapter: typeof import('./renderer/features/categories/api/category-adapter').categoryAdapter
  const categoryFormSchema: typeof import('./renderer/features/categories/model/category-form-schema').categoryFormSchema
  const categoryKeys: typeof import('./renderer/features/categories/hooks/category-keys').categoryKeys
  const categorySchema: typeof import('./renderer/features/categories/model/category-schema').categorySchema
  const categoryService: typeof import('./renderer/features/categories/services/category-service').categoryService
  const categoryToForm: typeof import('./renderer/features/categories/model/category-mappers').categoryToForm
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const formatCurrency: typeof import('./shared/utils/formatCurrency').formatCurrency
  const formatLempira: typeof import('./shared/utils/formatCurrency').formatLempira
  const forwardRef: typeof import('react').forwardRef
  const fromCents: typeof import('./shared/utils/currency').fromCents
  const fromUnitPrecision: typeof import('./shared/utils/quantity').fromUnitPrecision
  const getQuantityStep: typeof import('./shared/utils/quantity').getQuantityStep
  const hero: typeof import('./renderer/hero').default
  const imageAdapter: typeof import('./renderer/features/images/api/image-adapter').imageAdapter
  const imageService: typeof import('./renderer/features/images/services/image-service').imageService
  const inventoryAdapter: typeof import('./renderer/features/inventory/api/inventory-adapter').inventoryAdapter
  const inventoryEntrySchema: typeof import('./renderer/features/inventory/model/inventory-entry-schema').inventoryEntrySchema
  const inventoryItemSchema: typeof import('./renderer/features/inventory/model/inventory-entry-schema').inventoryItemSchema
  const inventoryKeys: typeof import('./renderer/features/inventory/hooks/inventory-keys').inventoryKeys
  const inventoryService: typeof import('./renderer/features/inventory/services/inventory-service').inventoryService
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const movementSchema: typeof import('./renderer/features/inventory/model/inventory-movement-schema').movementSchema
  const normalizeUnitPrecision: typeof import('./shared/utils/quantity').normalizeUnitPrecision
  const parseCurrency: typeof import('./shared/utils/formatCurrency').parseCurrency
  const parseError: typeof import('./shared/errors/parse-error').parseError
  const posInterface: typeof import('./renderer/features/pos/components/pos-interface').default
  const presentationFormSchema: typeof import('./renderer/features/presentations/model/presentation-form-schema').presentationFormSchema
  const presentationKeys: typeof import('./renderer/features/presentations/hooks/presentation-keys').presentationKeys
  const presentationSchema: typeof import('./renderer/features/presentations/model/presentation-schema').presentationSchema
  const presentationToForm: typeof import('./renderer/features/presentations/model/presentation-mappers').presentationToForm
  const presentationsAdapter: typeof import('./renderer/features/presentations/api/presentations-adapter').presentationsAdapter
  const presentationsService: typeof import('./renderer/features/presentations/services/presentations-service').presentationsService
  const productAdapter: typeof import('./renderer/features/products/api/product-adapter').productAdapter
  const productFormSchema: typeof import('./renderer/features/products/model/product-form-schema').productFormSchema
  const productKeys: typeof import('./renderer/features/products/hooks/product-keys').productKeys
  const productService: typeof import('./renderer/features/products/services/product-service').productService
  const productToForm: typeof import('./renderer/features/products/model/product-mappers').productToForm
  const purchaseOrderAdapter: typeof import('./renderer/features/purchase-orders/api/purchase-order-adapter').purchaseOrderAdapter
  const router: typeof import('./renderer/routes').router
  const sileo: typeof import('sileo').sileo
  const startTransition: typeof import('react').startTransition
  const supplierAdapter: typeof import('./renderer/features/suppliers/api/supplier-adapter').supplierAdapter
  const toCents: typeof import('./shared/utils/currency').toCents
  const toUnitPrecision: typeof import('./shared/utils/quantity').toUnitPrecision
  const toast: typeof import('sonner').toast
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useActiveCredits: typeof import('./renderer/features/credits/hooks/use-credits').useActiveCredits
  const useActiveCustomers: typeof import('./renderer/features/customers/hooks/use-customers').useActiveCustomers
  const useActiveSuppliers: typeof import('./renderer/features/suppliers/hooks/use-suppliers').useActiveSuppliers
  const useAddCreditPayment: typeof import('./renderer/features/credits/hooks/use-credits').useAddCreditPayment
  const useAddStock: typeof import('./renderer/features/inventory/hooks/use-add-stock').useAddStock
  const useAddToCustomerBalance: typeof import('./renderer/features/customers/hooks/use-customers').useAddToCustomerBalance
  const useApproveAdjustment: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useApproveAdjustment
  const useAvailableBatches: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useAvailableBatches
  const useBatchInfo: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useBatchInfo
  const useCalculateLateFees: typeof import('./renderer/features/credits/hooks/use-credits').useCalculateLateFees
  const useCallback: typeof import('react').useCallback
  const useCanExtendCredit: typeof import('./renderer/features/customers/hooks/use-customers').useCanExtendCredit
  const useCancelAdjustment: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useCancelAdjustment
  const useCancelCredit: typeof import('./renderer/features/credits/hooks/use-credits').useCancelCredit
  const useCancelOrder: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').useCancelOrder
  const useCategories: typeof import('./renderer/features/categories/hooks/use-categories').useCategories
  const useCategoryForm: typeof import('./renderer/features/categories/hooks/use-category-form').useCategoryForm
  const useContext: typeof import('react').useContext
  const useCreateCategory: typeof import('./renderer/features/categories/hooks/use-create-category').useCreateCategory
  const useCreateCredit: typeof import('./renderer/features/credits/hooks/use-credits').useCreateCredit
  const useCreateCustomer: typeof import('./renderer/features/customers/hooks/use-customers').useCreateCustomer
  const useCreateInventoryAdjustment: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useCreateInventoryAdjustment
  const useCreatePresentation: typeof import('./renderer/features/presentations/hooks/use-create-presentation').useCreatePresentation
  const useCreateProduct: typeof import('./renderer/features/products/hooks/use-create-product').useCreateProduct
  const useCreatePurchaseOrder: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').useCreatePurchaseOrder
  const useCreateSupplier: typeof import('./renderer/features/suppliers/hooks/use-suppliers').useCreateSupplier
  const useCredit: typeof import('./renderer/features/credits/hooks/use-credits').useCredit
  const useCredits: typeof import('./renderer/features/credits/hooks/use-credits').useCredits
  const useCreditsStats: typeof import('./renderer/features/credits/hooks/use-credits').useCreditsStats
  const useCustomer: typeof import('./renderer/features/customers/hooks/use-customers').useCustomer
  const useCustomerByDocument: typeof import('./renderer/features/customers/hooks/use-customers').useCustomerByDocument
  const useCustomerCredits: typeof import('./renderer/features/credits/hooks/use-credits').useCustomerCredits
  const useCustomers: typeof import('./renderer/features/customers/hooks/use-customers').useCustomers
  const useCustomersWithBalance: typeof import('./renderer/features/customers/hooks/use-customers').useCustomersWithBalance
  const useDebounce: typeof import('./shared/utils/debounce').useDebounce
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDeleteCategory: typeof import('./renderer/features/categories/hooks/use-delete-category').useDeleteCategory
  const useDeleteCredit: typeof import('./renderer/features/credits/hooks/use-credits').useDeleteCredit
  const useDeleteCustomer: typeof import('./renderer/features/customers/hooks/use-customers').useDeleteCustomer
  const useDeleteImage: typeof import('./renderer/features/images/hooks/use-delete-image').useDeleteImage
  const useDeleteInventoryAdjustment: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useDeleteInventoryAdjustment
  const useDeletePresentation: typeof import('./renderer/features/presentations/hooks/use-delete-presentation').useDeletePresentation
  const useDeleteProduct: typeof import('./renderer/features/products/hooks/use-delete-product').useDeleteProduct
  const useDeletePurchaseOrder: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').useDeletePurchaseOrder
  const useDeleteSupplier: typeof import('./renderer/features/suppliers/hooks/use-suppliers').useDeleteSupplier
  const useDisclosure: typeof import('@heroui/react').useDisclosure
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFieldArray: typeof import('react-hook-form').useFieldArray
  const useForm: typeof import('react-hook-form').useForm
  const useFormContext: typeof import('react-hook-form').useFormContext
  const useGenerateAdjustmentNumber: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useGenerateAdjustmentNumber
  const useGenerateCreditNumber: typeof import('./renderer/features/credits/hooks/use-credits').useGenerateCreditNumber
  const useGenerateOrderNumber: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').useGenerateOrderNumber
  const useGeneratePaymentNumber: typeof import('./renderer/features/credits/hooks/use-credits').useGeneratePaymentNumber
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImagePath: typeof import('./renderer/features/images/hooks/use-image-path').useImagePath
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useInventoryAdjustment: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useInventoryAdjustment
  const useInventoryAdjustments: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useInventoryAdjustments
  const useInventoryBatches: typeof import('./renderer/features/inventory/batches/hooks/use-inventory-batches').useInventoryBatches
  const useInventoryBatchesTable: typeof import('./renderer/features/inventory/batches/hooks/use-inventory-batches-table').useInventoryBatchesTable
  const useInventoryEntryForm: typeof import('./renderer/features/inventory/hooks/use-inventory-entry-form').useInventoryEntryForm
  const useInventoryMovements: typeof import('./renderer/features/inventory/hooks/use-inventory-movements').useInventoryMovements
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMarkOrderAsCompleted: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').useMarkOrderAsCompleted
  const useMemo: typeof import('react').useMemo
  const useMutation: typeof import('@tanstack/react-query').useMutation
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useOverdueCredits: typeof import('./renderer/features/credits/hooks/use-credits').useOverdueCredits
  const usePOSShortcuts: typeof import('./renderer/features/pos/hooks/use-pos-shortcuts').usePOSShortcuts
  const useParams: typeof import('react-router-dom').useParams
  const usePartialCredits: typeof import('./renderer/features/credits/hooks/use-credits').usePartialCredits
  const usePosPresentations: typeof import('./renderer/features/presentations/hooks/use-pos-presentations').usePosPresentations
  const usePresentationForm: typeof import('./renderer/features/presentations/hooks/use-presentation-form').usePresentationForm
  const usePresentationsByProduct: typeof import('./renderer/features/presentations/hooks/use-presentations-by-product').usePresentationsByProduct
  const useProductForm: typeof import('./renderer/features/products/hooks/use-product-form').useProductForm
  const useProducts: typeof import('./renderer/features/products/hooks/use-products').useProducts
  const useProductsFilters: typeof import('./renderer/features/products/hooks/use-products-filters').useProductsFilters
  const usePurchaseOrder: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').usePurchaseOrder
  const usePurchaseOrders: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').usePurchaseOrders
  const usePurchaseOrdersBySupplier: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').usePurchaseOrdersBySupplier
  const useQuery: typeof import('@tanstack/react-query').useQuery
  const useQueryClient: typeof import('@tanstack/react-query').useQueryClient
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useSendOrderToSupplier: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').useSendOrderToSupplier
  const useState: typeof import('react').useState
  const useSubtractFromCustomerBalance: typeof import('./renderer/features/customers/hooks/use-customers').useSubtractFromCustomerBalance
  const useSupplier: typeof import('./renderer/features/suppliers/hooks/use-suppliers').useSupplier
  const useSuppliers: typeof import('./renderer/features/suppliers/hooks/use-suppliers').useSuppliers
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useToggleCategoryStatus: typeof import('./renderer/features/categories/hooks/use-toggle-category-status').useToggleCategoryStatus
  const useTogglePresentation: typeof import('./renderer/features/presentations/hooks/use-toggle-presentation').useTogglePresentation
  const useToggleProduct: typeof import('./renderer/features/products/hooks/use-toggle-product').useToggleProduct
  const useTransition: typeof import('react').useTransition
  const useUpdateCategory: typeof import('./renderer/features/categories/hooks/use-update-category').useUpdateCategory
  const useUpdateCredit: typeof import('./renderer/features/credits/hooks/use-credits').useUpdateCredit
  const useUpdateCustomer: typeof import('./renderer/features/customers/hooks/use-customers').useUpdateCustomer
  const useUpdateCustomerBalance: typeof import('./renderer/features/customers/hooks/use-customers').useUpdateCustomerBalance
  const useUpdateInventoryAdjustment: typeof import('./renderer/features/inventory-adjustments/hooks/use-adjustments').useUpdateInventoryAdjustment
  const useUpdateOrderStatus: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').useUpdateOrderStatus
  const useUpdatePresentation: typeof import('./renderer/features/presentations/hooks/use-update-presentation').useUpdatePresentation
  const useUpdateProduct: typeof import('./renderer/features/products/hooks/use-update-product').useUpdateProduct
  const useUpdatePurchaseOrder: typeof import('./renderer/features/purchase-orders/hooks/use-purchase-orders').useUpdatePurchaseOrder
  const useUpdateSupplier: typeof import('./renderer/features/suppliers/hooks/use-suppliers').useUpdateSupplier
  const useUploadImage: typeof import('./renderer/features/images/hooks/use-upload-image').useUploadImage
  const zodResolver: typeof import('@hookform/resolvers/zod').zodResolver
}
// for type re-export
declare global {
  // @ts-ignore
  export type { CategoryFormInput, CategoryFormData } from './renderer/features/categories/model/category-form-schema'
  import('./renderer/features/categories/model/category-form-schema')
  // @ts-ignore
  export type { Category } from './renderer/features/categories/model/category-schema'
  import('./renderer/features/categories/model/category-schema')
  // @ts-ignore
  export type { AddStockPayload, ConsumeInventoryPayload, AdjustStockPayload } from './renderer/features/inventory/api/inventory-adapter'
  import('./renderer/features/inventory/api/inventory-adapter')
  // @ts-ignore
  export type { InventoryBatchFilters } from './renderer/features/inventory/batches/model/inventory-batch-filters'
  import('./renderer/features/inventory/batches/model/inventory-batch-filters')
  // @ts-ignore
  export type { InventoryBatch } from './renderer/features/inventory/batches/model/inventory-batch-schema'
  import('./renderer/features/inventory/batches/model/inventory-batch-schema')
  // @ts-ignore
  export type { InventoryBatchColumnKey, ColumnDef } from './renderer/features/inventory/batches/model/inventory-batches-columns'
  import('./renderer/features/inventory/batches/model/inventory-batches-columns')
  // @ts-ignore
  export type { InventoryEntryFormInput, InventoryEntryFormData } from './renderer/features/inventory/model/inventory-entry-schema'
  import('./renderer/features/inventory/model/inventory-entry-schema')
  // @ts-ignore
  export type { InventoryMovementFilters } from './renderer/features/inventory/model/inventory-movement-filters'
  import('./renderer/features/inventory/model/inventory-movement-filters')
  // @ts-ignore
  export type { InventoryMovement } from './renderer/features/inventory/model/inventory-movement-schema'
  import('./renderer/features/inventory/model/inventory-movement-schema')
  // @ts-ignore
  export type { InventoryMovementColumnKey, MovementColumnDef } from './renderer/features/inventory/movements/model/movement-columns'
  import('./renderer/features/inventory/movements/model/movement-columns')
  // @ts-ignore
  export type { POSFormInput, POSFormData } from './renderer/features/pos/components/pos-interface'
  import('./renderer/features/pos/components/pos-interface')
  // @ts-ignore
  export type { PaymentShortcutMethod } from './renderer/features/pos/hooks/use-pos-shortcuts'
  import('./renderer/features/pos/hooks/use-pos-shortcuts')
  // @ts-ignore
  export type { PresentationFormInput, PresentationFormData, PresentationFormMode } from './renderer/features/presentations/model/presentation-form-schema'
  import('./renderer/features/presentations/model/presentation-form-schema')
  // @ts-ignore
  export type { Presentation } from './renderer/features/presentations/model/presentation-schema'
  import('./renderer/features/presentations/model/presentation-schema')
  // @ts-ignore
  export type { ProductFormInput, ProductFormData } from './renderer/features/products/model/product-form-schema'
  import('./renderer/features/products/model/product-form-schema')
  // @ts-ignore
  export type { ProductStatus } from './renderer/features/products/model/product-status'
  import('./renderer/features/products/model/product-status')
  // @ts-ignore
  export type { UnitType } from './renderer/features/products/ui/product-units'
  import('./renderer/features/products/ui/product-units')
  // @ts-ignore
  export type { INavMainSubItem, INavMainItem } from './renderer/components/sidebar/nav-main'
  import('./renderer/components/sidebar/nav-main')
}
